package org.acme.enums;

public enum RequestTypes {
    AUTHENTICATE_USER, CREATE_SUPER_ADMIN, CREATE_ADMIN, CREATE_CLIENT, CREATE_ACCOUNT, GET_ACCOUNTS,
    CREATE_PRODUCT, GET_ALL_PRODUCTS, ADD_TO_CART
}
